apiVersion: v1
kind: Service
metadata:
  name: netie-inference-service
  namespace: netie-ai
spec:
  selector:
    app: netie-inference
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort
